"""added new

Revision ID: 6b4fba8a2bde
Revises: 9ff9a3406c2f
Create Date: 2024-03-05 13:12:02.399456

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get('SCHEMA')

# revision identifiers, used by Alembic.
revision = '6b4fba8a2bde'
down_revision = '9ff9a3406c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_educator_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('educator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['educator_id'], ['educators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE favorite_educator_list SET SCHEMA {SCHEMA};")
    op.drop_table('favorite_educator_lists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_educator_lists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('educator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['educator_id'], ['educators.id'], name='favorite_educator_lists_educator_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorite_educator_lists_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_educator_lists_pkey')
    )
    op.drop_table('favorite_educator_list')
    # ### end Alembic commands ###
