"""fixed location

Revision ID: 808e92c354e7
Revises: a3674fd907f4
Create Date: 2021-05-10 16:14:46.400273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '808e92c354e7'
down_revision = 'a3674fd907f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('lat', sa.Float(), nullable=False))
    op.add_column('locations', sa.Column('lng', sa.Float(), nullable=False))
    op.drop_column('locations', 'latitude')
    op.drop_column('locations', 'longtitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('longtitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('locations', sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('locations', 'lng')
    op.drop_column('locations', 'lat')
    # ### end Alembic commands ###
